// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmaf_fx3fZiQ9wwyGspenN3YV14JFHTms',
    appId: '1:706412148019:web:403d1f2bcd78eea1f07a46',
    messagingSenderId: '706412148019',
    projectId: 'slide-up-panel',
    authDomain: 'slide-up-panel.firebaseapp.com',
    storageBucket: 'slide-up-panel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqWyR6x_yZA7ndwuAY8Gi_gpOsC9asubM',
    appId: '1:706412148019:android:c819388ab18f9adef07a46',
    messagingSenderId: '706412148019',
    projectId: 'slide-up-panel',
    storageBucket: 'slide-up-panel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENeDdKw-nAty7A27VEbXycW9ooGs_Gzg',
    appId: '1:706412148019:ios:117de13d565c4ab5f07a46',
    messagingSenderId: '706412148019',
    projectId: 'slide-up-panel',
    storageBucket: 'slide-up-panel.appspot.com',
    iosClientId: '706412148019-gdk0d9rgsn39v48hud43gg4l5bio9go7.apps.googleusercontent.com',
    iosBundleId: 'com.example.slidinguppanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDENeDdKw-nAty7A27VEbXycW9ooGs_Gzg',
    appId: '1:706412148019:ios:117de13d565c4ab5f07a46',
    messagingSenderId: '706412148019',
    projectId: 'slide-up-panel',
    storageBucket: 'slide-up-panel.appspot.com',
    iosClientId: '706412148019-gdk0d9rgsn39v48hud43gg4l5bio9go7.apps.googleusercontent.com',
    iosBundleId: 'com.example.slidinguppanel',
  );
}
